/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq;

import edu.java.jooq.tables.Links;
import edu.java.jooq.tables.TgchatLinks;
import edu.java.jooq.tables.Tgchats;
import edu.java.jooq.tables.records.LinksRecord;
import edu.java.jooq.tables.records.TgchatLinksRecord;
import edu.java.jooq.tables.records.TgchatsRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LinksRecord> CONSTRAINT_4 =
        Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] {Links.LINKS.ID}, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_45 =
        Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_45"), new TableField[] {Links.LINKS.URL}, true);
    public static final UniqueKey<TgchatLinksRecord> TGCHAT_LINKS_PK =
        Internal.createUniqueKey(TgchatLinks.TGCHAT_LINKS,
            DSL.name("TGCHAT_LINKS_PK"),
            new TableField[] {TgchatLinks.TGCHAT_LINKS.TGCHATS_ID, TgchatLinks.TGCHAT_LINKS.LINKS_ID},
            true
        );
    public static final UniqueKey<TgchatsRecord> CONSTRAINT_D = Internal.createUniqueKey(Tgchats.TGCHATS,
        DSL.name("CONSTRAINT_D"),
        new TableField[] {Tgchats.TGCHATS.ID},
        true
    );

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TgchatLinksRecord, TgchatsRecord> CONSTRAINT_D6 = Internal.createForeignKey(
        TgchatLinks.TGCHAT_LINKS,
        DSL.name("CONSTRAINT_D6"),
        new TableField[] {TgchatLinks.TGCHAT_LINKS.TGCHATS_ID},
        Keys.CONSTRAINT_D,
        new TableField[] {Tgchats.TGCHATS.ID},
        true
    );
    public static final ForeignKey<TgchatLinksRecord, LinksRecord> CONSTRAINT_D65 = Internal.createForeignKey(
        TgchatLinks.TGCHAT_LINKS,
        DSL.name("CONSTRAINT_D65"),
        new TableField[] {TgchatLinks.TGCHAT_LINKS.LINKS_ID},
        Keys.CONSTRAINT_4,
        new TableField[] {Links.LINKS.ID},
        true
    );
}
