/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq;

import edu.java.jooq.tables.Links;
import edu.java.jooq.tables.TgchatLinks;
import edu.java.jooq.tables.Tgchats;
import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>LINKS</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>TGCHAT_LINKS</code>.
     */
    public static final TgchatLinks TGCHAT_LINKS = TgchatLinks.TGCHAT_LINKS;

    /**
     * The table <code>TGCHATS</code>.
     */
    public static final Tgchats TGCHATS = Tgchats.TGCHATS;
}
