/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq.tables.records;

import edu.java.jooq.tables.Tgchats;
import java.beans.ConstructorProperties;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TgchatsRecord extends UpdatableRecordImpl<TgchatsRecord> implements Record2<Long, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TGCHATS.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>TGCHATS.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>TGCHATS.CREATED_AT</code>.
     */
    public void setCreatedAt(@NotNull LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>TGCHATS.CREATED_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, LocalDateTime> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, LocalDateTime> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Tgchats.TGCHATS.ID;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field2() {
        return Tgchats.TGCHATS.CREATED_AT;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    @NotNull
    public TgchatsRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public TgchatsRecord value2(@NotNull LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public TgchatsRecord values(@Nullable Long value1, @NotNull LocalDateTime value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TgchatsRecord
     */
    public TgchatsRecord() {
        super(Tgchats.TGCHATS);
    }

    /**
     * Create a detached, initialised TgchatsRecord
     */
    @ConstructorProperties({"id", "createdAt"})
    public TgchatsRecord(@Nullable Long id, @NotNull LocalDateTime createdAt) {
        super(Tgchats.TGCHATS);

        setId(id);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TgchatsRecord
     */
    public TgchatsRecord(edu.java.jooq.tables.pojos.Tgchats value) {
        super(Tgchats.TGCHATS);

        if (value != null) {
            setId(value.getId());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
