/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq.tables;

import edu.java.jooq.DefaultSchema;
import edu.java.jooq.Keys;
import edu.java.jooq.tables.records.TgchatLinksRecord;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TgchatLinks extends TableImpl<TgchatLinksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TGCHAT_LINKS</code>
     */
    public static final TgchatLinks TGCHAT_LINKS = new TgchatLinks();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<TgchatLinksRecord> getRecordType() {
        return TgchatLinksRecord.class;
    }

    /**
     * The column <code>TGCHAT_LINKS.TGCHATS_ID</code>.
     */
    public final TableField<TgchatLinksRecord, Long> TGCHATS_ID =
        createField(DSL.name("tgchats_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>TGCHAT_LINKS.LINKS_ID</code>.
     */
    public final TableField<TgchatLinksRecord, Long> LINKS_ID =
        createField(DSL.name("links_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private TgchatLinks(Name alias, Table<TgchatLinksRecord> aliased) {
        this(alias, aliased, null);
    }

    private TgchatLinks(Name alias, Table<TgchatLinksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>TGCHAT_LINKS</code> table reference
     */
    public TgchatLinks(String alias) {
        this(DSL.name(alias), TGCHAT_LINKS);
    }

    /**
     * Create an aliased <code>TGCHAT_LINKS</code> table reference
     */
    public TgchatLinks(Name alias) {
        this(alias, TGCHAT_LINKS);
    }

    /**
     * Create a <code>TGCHAT_LINKS</code> table reference
     */
    public TgchatLinks() {
        this(DSL.name("tgchat_links"), null);
    }

    public <O extends Record> TgchatLinks(Table<O> child, ForeignKey<O, TgchatLinksRecord> key) {
        super(child, key, TGCHAT_LINKS);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<TgchatLinksRecord> getPrimaryKey() {
        return Keys.TGCHAT_LINKS_PK;
    }

    @Override
    @NotNull
    public List<ForeignKey<TgchatLinksRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_D6, Keys.CONSTRAINT_D65);
    }

    private transient Tgchats _tgchats;
    private transient Links _links;

    /**
     * Get the implicit join path to the <code>PUBLIC.TGCHATS</code> table.
     */
    public Tgchats tgchats() {
        if (_tgchats == null) {
            _tgchats = new Tgchats(this, Keys.CONSTRAINT_D6);
        }

        return _tgchats;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Links links() {
        if (_links == null) {
            _links = new Links(this, Keys.CONSTRAINT_D65);
        }

        return _links;
    }

    @Override
    @NotNull
    public TgchatLinks as(String alias) {
        return new TgchatLinks(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public TgchatLinks as(Name alias) {
        return new TgchatLinks(alias, this);
    }

    @Override
    @NotNull
    public TgchatLinks as(Table<?> alias) {
        return new TgchatLinks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TgchatLinks rename(String name) {
        return new TgchatLinks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TgchatLinks rename(Name name) {
        return new TgchatLinks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TgchatLinks rename(Table<?> name) {
        return new TgchatLinks(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
