/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TgchatLinks implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long tgchatsId;
    private Long linksId;

    public TgchatLinks() {
    }

    public TgchatLinks(TgchatLinks value) {
        this.tgchatsId = value.tgchatsId;
        this.linksId = value.linksId;
    }

    @ConstructorProperties({"tgchatsId", "linksId"})
    public TgchatLinks(
        @NotNull Long tgchatsId,
        @NotNull Long linksId
    ) {
        this.tgchatsId = tgchatsId;
        this.linksId = linksId;
    }

    /**
     * Getter for <code>TGCHAT_LINKS.TGCHATS_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTgchatsId() {
        return this.tgchatsId;
    }

    /**
     * Setter for <code>TGCHAT_LINKS.TGCHATS_ID</code>.
     */
    public void setTgchatsId(@NotNull Long tgchatsId) {
        this.tgchatsId = tgchatsId;
    }

    /**
     * Getter for <code>TGCHAT_LINKS.LINKS_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinksId() {
        return this.linksId;
    }

    /**
     * Setter for <code>TGCHAT_LINKS.LINKS_ID</code>.
     */
    public void setLinksId(@NotNull Long linksId) {
        this.linksId = linksId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TgchatLinks other = (TgchatLinks) obj;
        if (this.tgchatsId == null) {
            if (other.tgchatsId != null) {
                return false;
            }
        } else if (!this.tgchatsId.equals(other.tgchatsId)) {
            return false;
        }
        if (this.linksId == null) {
            if (other.linksId != null) {
                return false;
            }
        } else if (!this.linksId.equals(other.linksId)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.tgchatsId == null) ? 0 : this.tgchatsId.hashCode());
        result = prime * result + ((this.linksId == null) ? 0 : this.linksId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TgchatLinks (");

        sb.append(tgchatsId);
        sb.append(", ").append(linksId);

        sb.append(")");
        return sb.toString();
    }
}
